version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/theme/static_src/node_modules
    depends_on:
      - db
    restart: always
    command: >
      sh -c "
      until mysqladmin ping -h db -u root -proot --silent; do
        echo 'Waiting for MySQL...'; sleep 2;
      done;
      python manage.py migrate &&
      python manage.py tailwind start &&
      python manage.py runserver 0.0.0.0:8000
      "
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cnstyleshop
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
