services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    command: >
      sh -c "
      dockerize -wait tcp://db:3306 -timeout 60s &&
      python manage.py migrate &&
      exec python manage.py runserver 0.0.0.0:8000
      "
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  node_modules:
